
"""
ISSO NAO É UM COMENTÁRIO.
É UMA DOCSTRING
DIFERENTE DO COMENTÁRIO, UMA DOCSTRING É LIDA PELO COMPILADOR

"""
'''
PODE USAR 3 ASPAS SIMPLES OU DUPLAS
'''
#comentários em uma linha usa o HASHTAG
#Isso é um comentário em python